export default {
  USER_PASSWORD_INCORRECT: 'USER_PASSWORD_INCORRECT',
  USER_REGISTER_EXISTS: 'USER_REGISTER_EXISTS',
  OLD_PASSWORD_INCORRECT: 'OLD_PASSWORD_INCORRECT',
  EMAIL_NOT_EXISTS: 'EMAIL_NOT_EXISTS',
  CODE_NOT_EQUAL: 'CODE_NOT_EQUAL',
  ACCOUNT_NOT_ACTIVATED: 'ACCOUNT_NOT_ACTIVATED',
  ACCOUNT_DISABLE: 'ACCOUNT_DISABLE',
  ACCOUNT_DELETE: 'ACCOUNT_DELETE',
  ORGANIZATION_NOT_EXIST: 'ORGANIZATION_NOT_EXIST',
  ORGANIZATION_EXPIRED: 'ORGANIZATION_EXPIRED',
  ROLE_IN_USE: 'ROLE_IN_USE',
  
  EMAIL_EXITS:"EMAIL_EXITS",
  PHONE_EXITS:"PHONE_EXITS",
  PHONE_NOT_EXISTS: "PHONE_NOT_EXISTS",
  PHONE_MULTI_EXISTS: "PHONE_MULTI_EXISTS",
  NOT_SEND_OTP: "NOT_SEND_OTP",
  OTP_INCORRECT: "OTP_INCORRECT",
  OTP_VERIFIED: "OTP_VERIFIED",
  OTP_EXPIRED: "OTP_EXPIRED",
  FORBIDDEN: "Forbidden"
}
