export const TAB_KEYS = {
  EXCEEDED: 'EXCEEDED',
  LOST_SIGNAL: 'DATA_LOSS',
  SENSOR_ERROR: 'ERROR',
}

export const NOTIFY_TYPE = {
  SENSOR_GOOD: 'SENSOR_GOOD',
  SENSOR_ERROR: 'SENSOR_ERROR',
  DATA_EXCEEDED: 'DATA_EXCEEDED',
  DATA_EXCEEDED_PREPARED: 'DATA_EXCEEDED_PREPARED',
  DATA_GOOD: 'DATA_GOOD',
  DATA_LOSS: 'DATA_LOSS',
  DATA_CONNECTED: 'DATA_CONNECTED',
}
